# Generated by Django 6.0.1 on 2026-01-22 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Heading')),
                ('slug', models.SlugField(help_text='Post URL (Example: bali-trip)', unique=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='covers/', verbose_name='Cover')),
                ('location_name', models.CharField(help_text='Example: Bali, Indonesia', max_length=100, verbose_name='Location')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('is_published', models.BooleanField(default=False, verbose_name='Published')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('text', 'Text (Markdown)'), ('image', 'Image')], max_length=10, verbose_name='Block Type')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Serial Number')),
                ('text_content', models.TextField(blank=True, help_text='Supports Markdown', null=True, verbose_name='Text')),
                ('image_content', models.ImageField(blank=True, null=True, upload_to='post_images/', verbose_name='Image')),
                ('image_caption', models.CharField(blank=True, max_length=200, verbose_name='Photo Caption')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='blog.post')),
            ],
            options={
                'verbose_name': 'Content block',
                'verbose_name_plural': 'Content blocks',
                'ordering': ['position'],
            },
        ),
    ]
