# Generated by Django 6.0.1 on 2026-01-29 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(help_text='Post URL (Example: bali-trip)', max_length=300, unique=True),
        ),
    ]
