# Generated by Django 6.0.1 on 2026-02-09 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='continent',
            field=models.CharField(choices=[('Europe', 'Europe'), ('Asia', 'Asia'), ('Africa', 'Africa'), ('North America', 'North America'), ('South America', 'South America'), ('Oceania', 'Oceania'), ('Antarctica', 'Antarctica')], default='Europe', max_length=50, verbose_name='Continent'),
        ),
    ]
